APP.state = {
  data:              'https://example.com',
  errorCorrection:   'M',
  size:              320,
  margin:            16,
  dotStyle:          'square',
  cornerSquareStyle: 'square',
  cornerDotStyle:    'square',
  dotColor:          '#1A1714',
  dotColor2:         '#2D6A4F',
  useGradient:       false,
  gradientType:      'linear',
  bgColor:           '#FFFFFF',
  cornerSquareColor: '#1A1714',
  cornerDotColor:    '#2D6A4F',
  logoDataUrl:       null,
  logoSize:          0.20,
  format:            'png',
};
