name: 🕹️ Deploy Web Application

run-name: 🕹️ Deploy Web Application

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Web Application
    uses: albr21/gha-reusable-workflows/.github/workflows/reusable-deploy-web-application.yml@main
    permissions:
      pages: write
      id-token: write
      contents: read
    with:
      source-paths: |-
        src
        index.html
    secrets: inherit
